### ISSUE TITLE
Clarification on the inference forward pass

### ISSUE THREAD

**Issue by roysubhankar** [onuriel/PermutedAdaIN#1]
Hi,
Thanks for sharing the code. I have a question regarding the forward pass at inference stage.

The distribution of features that a subsequent layer sees during training is dependent on the previously applied padaIN normalization. 

> We apply pAdaIN to the output activations of all convolutional layers and in particular, before applying batch normalization

However, you write that: 

> pAdaIN is only applied during training time and not at test time

Why does the inference works when the distribution of features has changed (due to the absence of the pAdaIN layers)?

Thank you.

**Comment by onuriel** [comment]
Hi @roysubhankar,

Thanks for your interest in our work!

> Why does the inference works when the distribution of features has changed (due to the absence of the pAdaIN layers)?

That's a great question!

If the pAdaIN operation was always applied (p=1) then this would be the case, that is, there would be a 'domain shift' between training and inference. However, since every pAdaIN layer is applied with probability p, only some examples exhibit this distribution mismatch during training. Hence during training the model sees examples without these modifications as well. In fact, this is often the case since in practice, the best results are obtained with p=0.01.

Happy to answer any additional questions.

All the best

**Comment by roysubhankar** [comment]
Hi, Thanks for the response.

Right, applying with some probability makes sense. Got it.

I had another question. Are such methods (eg pAdaIN) only useful when the shape/geometry of the images do not change a lot? I am wondering, if the domain shift (mostly caused by change in geometry, rather the texture) is too high then changing styles wouldn't help much. What are your thoughts on this?

**Comment by onuriel** [comment]
You're welcome!

Yes, I tend to agree. This operation doesn't account for any geometric changes. As the statistics are calculated on the spatial dimensions and the channels (regardless of spatial position) are being shifted, thus the 'spatial' or geometric information should not change much. 

Coincidentally, a subsequent research direction touches on this very subject (currently a WIP and will be made public in the near future).

**Comment by roysubhankar** [comment]
Right, makes total sense. Thanks for all the clarifications and good luck.
