### ISSUE TITLE
Problems in segmentation results 

### ISSUE THREAD

**Issue by lixiaotong97** [onuriel/PermutedAdaIN#2]
Hi,
Thanks for sharing the great codes~ I run the SourceOnly experiments in FADA, but only get only  mIOU: 0.3709. I wonder if I miss some important issues, or the results should have some fluctuations due to different user training environment?
![image](https://user-images.githubusercontent.com/81090561/123575311-10e76100-d804-11eb-9007-4523dba8d60d.png)

the training script is:
```
export NGPUS=4
# train on source data
python -m torch.distributed.launch --nproc_per_node=$NGPUS train_src.py -cfg configs/deeplabv2_r101_src.yaml OUTPUT_DIR results/src_r101_padain_pretrained_0.01_tmp/
```

**Comment by onuriel** [comment]
Hi @lixiaotong97,

Thanks for your interest in our work!

There can be some fluctuations due to the user environment. You should be able to see a relative improvement regardless so just to be sure you can turn off pAdaIN in the feature extractor here : https://github.com/onuriel/PermutedAdaIN/blob/819cdb9ef4a42655934e5340c1479700be9cd6f3/FADA/core/models/feature_extractor.py#L48 
by setting with_permute_adain to False.

Also, If it helps, I can upload the source only model weights that achieved the results posted in the paper. Let me know.

Best of luck!

**Comment by lixiaotong97** [comment]
Thanks for the authors' kind response! 
In fact, I have run the FADA baseline before (use original code in github: https://github.com/JDAI-CV/FADA) , and got 0.3701 mIOU, meanwhile the pAdaIN result I run is 0.3709. These relative results make me a little confused.
![image](https://user-images.githubusercontent.com/81090561/123728802-7d2a9900-d8c6-11eb-9bd1-ee459d58dbc4.png)

I wonder if it's because the choice of using the last checkpoint to test, that caused the instability?  If it's convenient, it will be better to upload the SourceOnly model~ Thanks for your patient response!

Best of my wishes.

**Comment by lixiaotong97** [comment]
Hi~it seems that I found the question. I run the checkpoint in 14000, 16000, 18000, 20000 epoch and got 0.383, 0.373, 0.361, 0.371 mIOU, which demonstrates the importance to choose the checkpoint. If the sourceonly model uses the 20000(e.g. last) checkpoint? How do the authors do in the paper to choose the right checkpoint?

**Comment by onuriel** [comment]
Hi,

Oh I see, sorry for the confusion. We chose the last checkpoint.

The link to the checkpoint : https://drive.google.com/drive/folders/1z0OcjcLh4oJwEzao8YvBksQ87yw8V5L9?usp=sharing

Best of luck!

**Comment by lixiaotong97** [comment]
Thanks for your kind response！It might be some fluctuations ~ I think I have figured out my problems. Thanks again!

Best of my wishes.
